{% set version = "0.8.1" %}

package:
  name: pythonqwt
  version: {{ version }}

source:
  url: https://github.com/PierreRaybaut/PythonQwt/archive/v{{ version }}.tar.gz
  sha256: 798fffcbf53b62347eb9092ac48a5e77855dfe682dbe51a45a74f2be8479769e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - pyqt
    - numpy
    - sip
  run:
    - python
    - pyqt
    - numpy
    - sip

test:
  imports:
    - qwt
    - qwt.plot
    - qwt.qt

about:
  home: http://pierreraybaut.github.io/PythonQwt/
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: 'PythonQwt: Qt plotting widgets for Python'
  description: |
    The PythonQwt project was initiated to solve -at least temporarily- the
    obsolescence issue of PyQwt (the Python-Qwt C++ bindings library) which is
    no longer maintained. The idea was to translate the original Qwt C++ code
    to Python and then to optimize some parts of the code by writing new
    modules based on NumPy and other libraries.
  doc_url: https://pythonhosted.org/PythonQwt/
  dev_url: https://github.com/PierreRaybaut/PythonQwt

extra:
  recipe-maintainers:
    - marcelotrevisani
