{% set name = "PythonQwt" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PierreRaybaut/PythonQwt/archive/v{{ version }}.tar.gz
  sha256: ca3b4e34f51ade4681b99d73b5a9134498fee84a832e36cfd8f400b9acc07723
  patches:
    - removed_entry_points.patch

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - setuptools
    - python
    - pyqt  {{ pyqt_version }}
    - numpy
    - pip
  run:
    - python
    - pyqt  {{ pyqt_version }}
    - numpy

test:
  requires:
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
  imports:
    - qwt
    - qwt.tests
    - qwt.plot
    - qwt.qt

about:
  home: http://pierreraybaut.github.io/PythonQwt/
  license:  Qwt, Version 1.0
  license_file: LICENSE
  summary: 'PythonQwt: Qt plotting widgets for Python'
  description: |
    The PythonQwt project was initiated to solve -at least temporarily- the
    obsolescence issue of PyQwt (the Python-Qwt C++ bindings library) which is
    no longer maintained. The idea was to translate the original Qwt C++ code
    to Python and then to optimize some parts of the code by writing new
    modules based on NumPy and other libraries.
  doc_url: https://pythonhosted.org/PythonQwt/
  dev_url: https://github.com/PierreRaybaut/PythonQwt

extra:
  recipe-maintainers:
    - marcelotrevisani
